# Generated by Django 4.2.7 on 2023-11-12 21:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrisapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Employment",
            new_name="Contact",
        ),
    ]
