# Generated by Django 4.2.7 on 2023-11-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrisapp", "0006_alter_event_options_remove_event_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
