# Generated by Django 4.2.7 on 2023-12-03 20:31

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrisapp", "0008_delete_contact_delete_credential_event_receiver"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="From",
            field=models.CharField(
                default='test',
                max_length=200,
            ),
        ),
    ]
