# Generated by Django 4.2.7 on 2023-12-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrisapp", "0012_remove_event_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="From",
            field=models.CharField(default="Admin", max_length=30),
        ),
    ]
