# Generated by Django 4.2.7 on 2023-12-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrisapp", "0013_event_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="From",
            field=models.CharField(default="Admin", editable=False, max_length=30),
        ),
    ]
