# Generated by Django 4.2.7 on 2023-12-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrisapp", "0014_alter_event_from"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sendto",
                    models.CharField(
                        choices=[
                            ("Manager", "Manager"),
                            ("Human Resources", "Human Resources"),
                        ],
                        max_length=30,
                    ),
                ),
                ("From", models.CharField(editable=False, max_length=30)),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("Schedule Change", "Schedule Change"),
                            ("Availability", "Availability"),
                            ("Request Meeting", "Request Meeting"),
                        ],
                        max_length=30,
                    ),
                ),
                ("content", models.TextField()),
            ],
        ),
    ]
