# Generated by Django 4.2.7 on 2023-12-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrisapp", "0015_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("From", models.CharField(editable=False, max_length=30)),
                ("topic", models.CharField(max_length=200)),
                ("content", models.TextField()),
            ],
        ),
    ]
