# Generated by Django 4.2.7 on 2023-11-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrisapp", "0002_rename_employment_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credentials",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=200)),
                ("lastname", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("pw", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="contact",
            name="address",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="phone",
        ),
    ]
