# Generated by Django 4.2.7 on 2023-11-13 03:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrisapp", "0003_credentials_remove_contact_address_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Credentials",
            new_name="Credential",
        ),
    ]
