# Generated by Django 4.2.7 on 2023-12-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    (1, "Employee"),
                    (2, "Manager"),
                    (3, "Human Resource Officer"),
                    (4, "Temp Manager"),
                    (5, "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
