# Generated by Django 4.2.7 on 2023-12-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_alter_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("Employee", "Employee"),
                    ("Manager", "Manager"),
                    ("Human Resource Officer", "Human Resource Officer"),
                    ("Temp Manager", "Temp Manager"),
                    ("Admin", "Admin"),
                ],
                max_length=30,
            ),
        ),
    ]
